(() => {
  const $ = id => document.getElementById(id);
  let offset = 0, total = 0;
  const tableNames = ['tq_levels','tq_quotas','tq_limits','tq_assignments','tq_services','tq_service_members','tq_clients','tq_usage','tq_tokens','tq_token_items','tq_ledger'];
  const operations = {
    quota: {label:'Quota',path:v=>`/v1/admin/tenants/${encodeURIComponent(v.tenant)}/quotas/${encodeURIComponent(v.quota_code)}`, fields:[['quota_code','Quota code','text'],['unit_code','单位（use）','text'],['metering_mode','计量模式','select','per_use,reported_usage']], body:v=>({unit_code:v.unit_code,metering_mode:v.metering_mode})},
    level: {label:'Level',path:v=>`/v1/admin/tenants/${encodeURIComponent(v.tenant)}/levels/${encodeURIComponent(v.level_code)}`, fields:[['level_code','Level code','text']],body:()=>({})},
    limit: {label:'Limit',path:v=>`/v1/admin/tenants/${encodeURIComponent(v.tenant)}/levels/${encodeURIComponent(v.level_code)}/limits/${encodeURIComponent(v.quota_code)}`,fields:[['level_code','Level code','text'],['quota_code','Quota code','text'],['limit_mode','限额模式','select','finite,unlimited'],['limit_value','限额（unlimited 时留空）','number'],['period_kind','周期','select','day,month,level_term'],['timezone','时区','text']],body:v=>({limit_mode:v.limit_mode,limit_value:v.limit_value===''?null:Number(v.limit_value),period_kind:v.period_kind,timezone:v.timezone||'Asia/Shanghai'})},
    service: {label:'Service',path:v=>`/v1/admin/tenants/${encodeURIComponent(v.tenant)}/services/${encodeURIComponent(v.service_code)}`,fields:[['service_code','Service code','text'],['quota_code','Quota code（子项可留空）','text'],['service_kind','种类','select','atomic,composite'],['redemption_mode','兑现模式','select','instant,durable'],['charge_units','开场扣费量（instant 留空）','number'],['session_ttl_seconds','默认持续秒数（可留空）','number']],body:v=>({quota_code:v.quota_code||null,service_kind:v.service_kind,redemption_mode:v.redemption_mode,charge_units:v.charge_units===''?null:Number(v.charge_units),session_ttl_seconds:v.session_ttl_seconds===''?null:Number(v.session_ttl_seconds)})},
    member: {label:'组合成员',path:v=>`/v1/admin/tenants/${encodeURIComponent(v.tenant)}/services/${encodeURIComponent(v.parent)}/members/${encodeURIComponent(v.child)}`,fields:[['parent','父 Service code','text'],['child','子 Service code','text'],['max_uses','本场最多次数（留空为不限）','number']],body:v=>({max_uses:v.max_uses===''?null:Number(v.max_uses)})},
    assignment: {label:'用户等级',path:v=>`/v1/admin/tenants/${encodeURIComponent(v.tenant)}/subjects/${encodeURIComponent(v.subject_id)}/level`,fields:[['subject_id','用户 ID','number'],['level_code','Level code','text'],['effective_at','生效时间（ISO，可留空）','text'],['expires_at','到期时间（ISO，可留空）','text'],['renew_term','开启新会期','checkbox']],body:v=>({level_code:v.level_code,effective_at:v.effective_at||null,expires_at:v.expires_at||null,renew_term:v.renew_term})}
  };
  const api = async (path,options={}) => {
    const key=$('admin-key').value.trim();
    if (!key) throw Error('请输入管理员密钥');
    const response=await fetch(path,{...options,headers:{Authorization:`Bearer ${key}`,...(options.body?{'Content-Type':'application/json'}:{})},cache:'no-store'});
    if (!response.ok) throw Error(`${response.status}: ${await response.text()}`);
    return response;
  };
  const tenant=()=>{const value=$('tenant').value.trim();if(!value)throw Error('请输入租户');return value;};
  const show=(id,value)=>{$(id).textContent=value;};
  $('connect').onclick=async()=>{try{const r=await api('/v1/admin/tables');const data=await r.json();show('connection',`已连接 · ${data.tables.length} 张表`);await load();}catch(e){show('connection',e.message);}};
  document.querySelectorAll('nav button').forEach(button=>button.onclick=()=>{document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b===button));document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('hidden',p.id!==button.dataset.tab));});
  tableNames.forEach(name=>{const option=document.createElement('option');option.value=name;option.textContent=name;$('table-name').append(option);});
  async function load(){try{const name=$('table-name').value;const r=await api(`/v1/admin/tables/${name}?tenant=${encodeURIComponent(tenant())}&limit=100&offset=${offset}`);const data=await r.json();total=data.total;const head=$('table-head'),body=$('table-body');head.replaceChildren();body.replaceChildren();const tr=document.createElement('tr');data.columns.forEach(column=>{const th=document.createElement('th');th.textContent=column;tr.append(th);});head.append(tr);data.rows.forEach(row=>{const tr=document.createElement('tr');data.columns.forEach(column=>{const td=document.createElement('td');td.textContent=row[column]===undefined?'':String(row[column]);tr.append(td);});body.append(tr);});show('page-status',`${offset+1}–${Math.min(offset+100,total)} / ${total}`);}catch(e){show('page-status',e.message);}}
  $('refresh').onclick=()=>{offset=0;load();};$('table-name').onchange=()=>{offset=0;load();};$('previous').onclick=()=>{offset=Math.max(0,offset-100);load();};$('next').onclick=()=>{if(offset+100<total){offset+=100;load();}};
  Object.entries(operations).forEach(([key,op])=>{const option=document.createElement('option');option.value=key;option.textContent=op.label;$('operation').append(option);});
  function renderFields(){const op=operations[$('operation').value];const parent=$('fields');parent.replaceChildren();op.fields.forEach(([key,label,type,choices])=>{const wrapper=document.createElement('label');wrapper.textContent=label;let input;if(type==='select'){input=document.createElement('select');choices.split(',').forEach(choice=>{const option=document.createElement('option');option.value=choice;option.textContent=choice;input.append(option);});}else{input=document.createElement('input');input.type=type;if(type==='number')input.min='0';}input.id=`field-${key}`;wrapper.append(input);parent.append(wrapper);});} $('operation').onchange=()=>{renderFields();$('delete-member').hidden=$('operation').value!=='member';};renderFields();$('delete-member').hidden=true;
  $('save').onclick=async()=>{try{const op=operations[$('operation').value],v={tenant:tenant()};op.fields.forEach(([key,,type])=>v[key]=type==='checkbox'?$('field-'+key).checked:$('field-'+key).value.trim());const response=await api(op.path(v),{method:'PUT',body:JSON.stringify(op.body(v))});show('config-result',JSON.stringify(await response.json(),null,2));await load();}catch(e){show('config-result',e.message);}};
  $('delete-member').onclick=async()=>{try{const parent=$('field-parent').value.trim(),child=$('field-child').value.trim();if(!parent||!child)throw Error('请输入父子 Service code');if(!confirm(`删除 ${parent} → ${child} 的组合映射？已签发凭证的快照仍有效。`))return;const path=`/v1/admin/tenants/${encodeURIComponent(tenant())}/services/${encodeURIComponent(parent)}/members/${encodeURIComponent(child)}`;await api(path,{method:'DELETE'});show('config-result','已删除组合映射');await load();}catch(e){show('config-result',e.message);}};
  $('provision').onclick=async()=>{try{const id=$('client-id').value.trim();if(!id)throw Error('请输入 Client ID');const response=await api(`/v1/admin/clients/${encodeURIComponent(id)}/provision`,{method:'POST',body:JSON.stringify({tenant_id:tenant(),service_code:$('client-service').value.trim(),role:$('client-role').value,base_url:$('base-url').value.trim(),rotate:$('rotate').checked})});const blob=await response.blob();const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`${id}-quotakit.md`;link.click();setTimeout(()=>URL.revokeObjectURL(url),60000);show('client-result','已下载。请立即安全保存；此页面无法再次读取明文密钥。');await load();}catch(e){show('client-result',e.message);}};
})();